#!/bin/sh

# Set these paths appropriately

BIN="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/bin"
CMD="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/cmd"
LIB="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/albanian-abbreviations
PARFILE=${LIB}/albanian.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
