#!/bin/sh

# Set these paths appropriately

BIN="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/bin"
CMD="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/cmd"
LIB="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german.par
LEXFILE=${LIB}/german-lexicon.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
