#!/bin/sh

# Set these paths appropriately

BIN="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/bin"
CMD="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/cmd"
LIB="/home/livio24/Documents/Crime-event-localization-and-deduplication/Crime_Ingestion_App/configuration/tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/ukrainian-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ukrainian.par

# do tokenization
$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
